site_name: Reroute documentation
pages:
- [index.md, Introduction, Quickstart]
- [router.md, API reference, Router]
- [state.md, API reference, State]
- [url.md, API reference, URL]

theme: readthedocs
